apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongocfg-0-0
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mongodb/cfg0-0"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-mongodb-0-0