apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-1-2
spec:
  storageClassName: local-storage
  capacity:
    storage: 700Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mongodb/rs1-2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-mongodb-1-2