apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.abac_log_consumer.name }}
  labels:
    app: {{ .Values.abac_log_consumer.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.abac_log_consumer.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.abac_log_consumer.name }}
    spec:
      containers:
      - name: {{ .Values.abac_log_consumer.name }}
        image: {{ .Values.abac_log_consumer.repository }}:{{ .Values.abac_log_consumer.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["POD_A_RECORD"]
        args: ["export POD_A_RECORD=$(echo $POD_IP | sed 's/\\./\\-/g') && /app/bin/abac_log_consumer foreground"]
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        {{- range $name, $value := .Values.env_abac_log_consumer }}
        {{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: {{ .Values.resources_abac_log_consumer.cpu }}
            memory: {{ .Values.resources_abac_log_consumer.memory }}
          limits:
            cpu: {{ .Values.resources_abac_log_consumer.cpu_limit }}
            memory: {{ .Values.resources_abac_log_consumer.memory_limit }}
