apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: {{ .Values.abac_api.name }}
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.abac_api.name }}
  type: ClusterIP