apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    version: {{ .Values.image_api.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        version: {{ .Values.image_api.tag }}
    spec:
      containers:
      - name: em-api
        image: {{ .Values.image_api.repository }}:{{ .Values.image_api.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        # Phoenix
        - name: PORT
          value: "{{ .Values.env_api.port }}"
        - name: HOST
          value: "{{ .Values.env_api.host }}"
        - name: SECRET_KEY
          value: "{{ .Values.env_api.secret }}"
        - name: ERLANG_COOKIE
          value: "{{ .Values.env_api.ERLANG_COOKIE }}"
        # Database
        - name: EVENT_MANAGER_DB_NAME
          value: "{{ .Values.env_db.POSTGRES_DB }}"
        - name: EVENT_MANAGER_DB_USER
          value: "{{ .Values.env_db.POSTGRES_USER }}"
        - name: EVENT_MANAGER_DB_PASSWORD
 {{- if .Values.env_db.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db.POSTGRES_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
        - name: EVENT_MANAGER_DB_HOST
          value: "{{ .Values.env_api.DB_HOST }}"
        - name: EVENT_MANAGER_DB_PORT
          value: "{{ .Values.env_api.DB_PORT }}"
        - name: EVENT_MANAGER_DB_POOL_SIZE
          value: "{{ .Values.env_api.DB_POOL_SIZE }}"
        # App migrations
        - name: DB_MIGRATE
          value: "{{ .Values.env_api.DB_MIGRATE }}"
        - name: MAX_EVENTS
          value: "{{ .Values.env_api.MAX_EVENTS }}"
        resources:
          requests:
            cpu: {{ .Values.resources_api.cpu }}
            memory: {{ .Values.resources_api.memory }}
          limits:
            cpu: {{ .Values.resources_api.cpu_limit }}
            memory: {{ .Values.resources_api.memory_limit }}
        readinessProbe:
          timeoutSeconds: 2
          initialDelaySeconds: 5
          failureThreshold: 3
          tcpSocket:
            port: 4000
        livenessProbe:
          timeoutSeconds: 2
          initialDelaySeconds: 5
          failureThreshold: 3
          tcpSocket:
            port: 4000
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgres
              topologyKey: failure-domain.beta.kubernetes.io/zone
