apiVersion: v1
kind: Service
metadata:
  # namespace: ael
  name: api-svc
  labels:
    app: api
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: api
  type: ClusterIP
