apiVersion: v1
kind: Service
metadata:
  name: arb-cfg0
  labels:
    app: mongodb-replicaset
    component: arb-cfg0
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb-replicaset
    component: arb-cfg0