apiVersion: v1
kind: Service
metadata:
  name: arb-1-sh1
  labels:
    app: mongodb-replicaset
    component: arb-1-sh1
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb-replicaset
    component: arb-1-sh1