apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: me-db
  labels:
    app: mongodb-replicaset
  name: mongos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-replicaset
        component: mongos
    spec:
      containers:
        - name: mongos
          image: mongo:4.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
          command:
            - mongos
            - --configdb=cfg0/mongodb-cfg-mongodb-replicaset-0.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017,mongodb-cfg-mongodb-replicaset-1.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017,mongodb-cfg-mongodb-replicaset-2.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017,mongodb-cfg-mongodb-replicaset-3.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017,mongodb-cfg-mongodb-replicaset-4.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017,mongodb-cfg-mongodb-replicaset-5.mongodb-cfg-mongodb-replicaset.me-db.svc.cluster.local:27017
            - --port=27017
            - --bind_ip=0.0.0.0
            - --keyFile=/data/configdb/key.txt
          volumeMounts:
            - name: configdir
              mountPath: /data/configdb
      volumes:
        - name: keydir
          secret:
            defaultMode: 0400
            secretName: mongodb-sh0-mongodb-replicaset-keyfile
        - name: workdir
          emptyDir: {}
        - name: configdir
          emptyDir: {}
      initContainers:
        - name: copy-config
          image: busybox
          command:
            - "sh"
          args:
            - "-c"
            - |
              set -e
              set -x
              cp /keydir-readonly/key.txt /data/configdb/key.txt
              chmod 600 /data/configdb/key.txt
          volumeMounts:
            - name: keydir
              mountPath: /keydir-readonly
            - name: configdir
              mountPath: /data/configdb
      nodeSelector:
        databases: mongodb