apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv-mongo-primary-shard0
spec:
  capacity:
    storage: 1200Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  #volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mongodb-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-me-0