apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-0-0
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mongodb/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-mongodb-0-0