apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-primary
spec:
  storageClassName: local-storage
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mongodb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-cluster-1-pool-1-2c47a5a6-tknl