apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-cfg-2
spec:
  storageClassName: local-storage
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mongodb-cfg/cfg-2"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-me-1