apiVersion: v1
kind: Service
metadata:
  namespace: il
  name: graphql-svc
  labels:
    app: graphql
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: graphql
  type: ClusterIP
