apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.image_ops_scheduler.deployment }}
  labels:
    app: {{ .Values.image_ops_scheduler.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.image_ops_scheduler.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.image_ops_scheduler.name }}
    spec:
      containers:
      - name: {{ .Values.image_ops_scheduler.name }}
        image: {{ .Values.image_ops_scheduler.repository }}:{{ .Values.image_ops_scheduler.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["POD_A_RECORD"]
        args: ["export POD_A_RECORD=$(echo $POD_IP | sed 's/\\./\\-/g') && /app/bin/ops_scheduler foreground"]
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        {{- range $name, $value := .Values.env_scheduler }}
        {{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        - name: NAMESPACE
          value: "{{ .Values.env_api.NAMESPACE }}"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DB_PASSWORD
        {{- if .Values.env_db.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db.POSTGRES_PASSWORD }}"
        {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
        {{- end }}
        - name: BLOCK_DB_PASSWORD
        {{- if .Values.env_db.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db.POSTGRES_PASSWORD }}"
        {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD_BLOCK
        {{- end }}
        - name: EVENT_MANAGER_DB_PASSWORD
        {{- if .Values.env_api.EVENT_MANAGER_DB_PASSWORD }}
          value: "{{ .Values.env_api.EVENT_MANAGER_DB_PASSWORD }}"
        {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: EM_PASSWORD
        {{- end }}
        - name: READ_DB_PASSWORD
  {{- if .Values.env_db.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db.POSTGRES_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
        - name: IL_ENDPOINT
          value: "{{ .Values.env_api.IL_ENDPOINT }}"
        resources:
          requests:
            cpu: {{ .Values.resources_ops_scheduler.cpu }}
            memory: {{ .Values.resources_ops_scheduler.memory }}
          limits:
            cpu: {{ .Values.resources_ops_scheduler.cpu_limit }}
            memory: {{ .Values.resources_ops_scheduler.memory_limit }}
