apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.image_me_transactions.name }}
  labels:
    app: {{ .Values.image_me_transactions.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.image_me_transactions.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.image_me_transactions.name }}
    spec:
      containers:
      - name: {{ .Values.image_me_transactions.name }}
        image: {{ .Values.image_me_transactions.repository }}:{{ .Values.image_me_transactions.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        {{- if eq .Values.env_me_transactions.DEBUG "true"}}
        args: ["epmd -daemon && export NODE_NAME=me_transactions@$(echo $POD_IP | sed 's/\\./\\-/g').me.pod.cluster.local && /root/me_transactions_build -trace.node"]
        {{- end }}
        {{- if eq .Values.env_me_transactions.DEBUG "false"}}
        args: ["epmd -daemon && export NODE_NAME=me_transactions@$(echo $POD_IP | sed 's/\\./\\-/g').me.pod.cluster.local && /root/me_transactions_build"]
        {{- end }}
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        {{- range $name, $value := .Values.env_me_transactions }}
        {{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: {{ .Values.resources_api.cpu }}
            memory: {{ .Values.resources_api.memory }}
          limits:
            cpu: {{ .Values.resources_api.cpu_limit }}
            memory: {{ .Values.resources_api.memory_limit }}
        {{- if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector_api}}
        {{ end }}
