apiVersion: v1
kind: Service
metadata:
  namespace: digital-signature
  name: api-svc
  labels:
    app: ds-api
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.image_api.name }}
  type: ClusterIP
