apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zookeeper-0
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/kafka-0/zookeeper/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-kafka-0