apiVersion: v1
kind: Service
metadata:
  name: cache-svc
  labels:
    app: cache
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: cache
  type: ClusterIP
