apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: person-deactivator
  labels:
    app: person-deactivator
    version: {{ .Values.image_person_deactivator.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: person-deactivator
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-deactivator
        version: {{ .Values.image_person_deactivator.tag }}
    spec:
      containers:
      - name: person-deactivator
        image: {{ .Values.image_person_deactivator.repository }}:{{ .Values.image_person_deactivator.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args: ["export POD_A_RECORD=$(echo $POD_IP | sed 's/\\./\\-/g') && /app/bin/person_deactivator foreground"]
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        {{- range $name, $value := .Values.env_person_deactivator }}
        {{- if not (empty $value) }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        # RPC env
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DB_PASSWORD
  {{- if .Values.env_person_deactivator.DB_PASSWORD }}
          value: "{{ .Values.env_person_deactivator.DB_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
        - name: DB_DEDUPLICATION_PASSWORD
  {{- if .Values.env_db_dedup.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db_dedup.POSTGRES_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
        - name: DB_READ_PASSWORD
  {{- if .Values.env_person_deactivator.DB_READ_PASSWORD }}
          value: "{{ .Values.env_person_deactivator.DB_READ_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
          requests:
            cpu: {{ .Values.resources_api.cpu }}
            memory: {{ .Values.resources_api.memory }}
          limits:
            cpu: {{ .Values.resources_api.cpu_limit }}
            memory: {{ .Values.resources_api.memory_limit }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgresql
              topologyKey: failure-domain.beta.kubernetes.io/zone
        {{- if .Values.nodeSelector_api }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector_api}}
        {{ end }}
