apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: verification
  name: api
  labels:
    app: api
    version: {{ .Values.image_api.tag }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        version: {{ .Values.image_api.tag }}
    spec:
      containers:
      - name: verification-api
        image:  {{ .Values.image_api.repository }}:{{ .Values.image_api.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        # Phoenix
        - name: PORT
          value: "{{ .Values.env_api.port }}"
        - name: HOST
          value: "{{ .Values.env_api.host }}"
        - name: SECRET_KEY
          value: "{{ .Values.env_api.secret }}"
        - name: ERLANG_COOKIE
          value: "{{ .Values.env_api.ERLANG_COOKIE }}"
        # Database
        - name: DB_NAME
          value: "{{ .Values.env_db.POSTGRES_DB }}"
        - name: DB_USER
          value: "{{ .Values.env_db.POSTGRES_USER }}"
        - name: DB_PASSWORD
  {{- if .Values.env_db.POSTGRES_PASSWORD }}
          value: "{{ .Values.env_db.POSTGRES_PASSWORD }}"
  {{ else }}
          valueFrom:
             secretKeyRef:
               name: db
               key: DB_PASSWORD
  {{ end }}
        - name: DB_HOST
          value: "{{ .Values.env_api.DB_HOST }}"
        - name: DB_PORT
          value: "{{ .Values.env_api.DB_PORT }}"
        - name: DB_POOL_SIZE
          value: "{{ .Values.env_api.DB_POOL_SIZE }}"
        - name: GATEWAY_ADAPTER
          value: "{{ .Values.env_api.GATEWAY_ADAPTER }}"
        - name: SOURCE_NUMBER
          value: "{{ .Values.env_api.SOURCE_NUMBER }}"
        - name: GATEWAY_URL
          value: "{{ .Values.env_api.GATEWAY_URL }}"
        - name: GATEWAY_STATUS_URL
          value: "{{ .Values.env_api.GATEWAY_STATUS_URL }}"
        - name: GATEWAY_LOGIN
          value: "{{ .Values.env_api.GATEWAY_LOGIN }}"
        - name: GATEWAY_PASSWORD
          value: "{{ .Values.env_api.GATEWAY_PASSWORD }}"
        - name: TWILIO_ACCOUNT_SID
          value: "{{ .Values.env_api.TWILIO_ACCOUNT_SID }}"
        - name: TWILIO_AUTH_TOKEN
          value: "{{ .Values.env_api.TWILIO_AUTH_TOKEN }}"
        - name: CODE_EXPIRATION_PERIOD_MINUTES
          value: "{{ .Values.env_api.CODE_EXPIRATION_PERIOD_MINUTES }}"
        # App migrations
        - name: DB_MIGRATE
          value: "true"
        resources:
          requests:
            cpu: {{ .Values.resources_api.cpu }}
            memory: {{ .Values.resources_api.memory }}
          limits:
            cpu: {{ .Values.resources_api.cpu_limit }}
            memory: {{ .Values.resources_api.memory_limit }}
        readinessProbe:
          timeoutSeconds: 2
          initialDelaySeconds: 5
          failureThreshold: 3
          tcpSocket:
            port: 4000
        livenessProbe:
          timeoutSeconds: 2
          initialDelaySeconds: 5
          failureThreshold: 3
          tcpSocket:
            port: 4000
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: postgres
              topologyKey: failure-domain.beta.kubernetes.io/zone
        {{- if or (eq .Values.env "prod") (eq .Values.env "preprod") }}
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodeSelector_api}}
        {{ end }}
