
## API ##
#Docker image and tag for api
image_api:
  repository: edenlabllc/ops
  tag: "2.9.1"

image_ops_scheduler:
  repository: edenlabllc/ops_scheduler
  tag: "1.4.0"
  name: "scheduler"
  deployment: "ops-scheduler"

image_deactivate_declaration_consumer:
  repository: edenlabllc/deactivate_declaration_consumer
  tag: "1.3.0"
  name: "deactivate-declaration-consumer"

env_api:
  # RPC env
  NAMESPACE: "ops"
   # --- Phoenix---#
   #APP_PORT
  port: "4000"
  #APP_HOST
  host: ""
  #APP_SECRET_KEY
  secret: ""
  ERLANG_COOKIE: ""
      # Database
  DB_NAME: "ops"
  DB_USER: "db"
  DB_PASSWORD: ""
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
      # READ Database
  READ_DB_NAME: "ops"
  READ_DB_USER: "db"
  READ_DB_PASSWORD: ""
  READ_DB_HOST: "db-svc"
  READ_DB_PORT: "5432"
  READ_DB_POOL_SIZE: "50"
    # Blocks database
  BLOCK_DB_NAME: "blocks"
  BLOCK_DB_USER: "db"
  BLOCK_DB_PASSWORD: ""
  BLOCK_DB_HOST: "blocks-db-svc"
  BLOCK_DB_PORT: "5432"
  BLOCK_DB_POOL_SIZE: "50"
  # EventManager Database
  EVENT_MANAGER_DB_NAME: "event_manager"
  EVENT_MANAGER_DB_USER: "db"
  EVENT_MANAGER_DB_PASSWORD: ""
  EVENT_MANAGER_DB_HOST: "db-svc.em.svc.cluster.local"
  EVENT_MANAGER_DB_PORT: "5432"
  EVENT_MANAGER_DB_POOL_SIZE: "50"
  DECLARATION_AUTOTERMINATION_SCHEDULE: "*/15 * * * *"
  DECLARATION_AUTO_APPROVE_SCHEDULE: "*/15 * * * *"
  CLOSE_BLOCK_SCHEDULE: "0 0 * * *"
  EM_ENABLED: true
    # App migrations
  DB_MIGRATE: "true"
  IL_ENDPOINT: "api-svc.il.svc.cluster.local"

env_image_deactivate_declaration_consumer:
  ERLANG_COOKIE: "admin"
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  DB_NAME: "ops"
  DB_USER: "db"
  DB_PASSWORD: ""
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
  BLOCK_DB_NAME: "blocks"
  BLOCK_DB_USER: "db"
  BLOCK_DB_PASSWORD: ""
  BLOCK_DB_HOST: "blocks-db-svc"
  BLOCK_DB_PORT: "5432"
  BLOCK_DB_POOL_SIZE: "50"
  EVENT_MANAGER_DB_NAME: "event_manager"
  EVENT_MANAGER_DB_USER: "db"
  EVENT_MANAGER_DB_PASSWORD: ""
  EVENT_MANAGER_DB_HOST: "db-svc.em.svc.cluster.local"
  EVENT_MANAGER_DB_PORT: "5432"
  EVENT_MANAGER_DB_POOL_SIZE: "50"
      # READ Database
  READ_DB_NAME: "ops"
  READ_DB_USER: "db"
  READ_DB_PASSWORD: ""
  READ_DB_HOST: "db-svc"
  READ_DB_PORT: "5432"
  READ_DB_POOL_SIZE: "50"

env_scheduler:
  #APP_SECRET_KEY
  ERLANG_COOKIE: ""
  DECLARATION_AUTO_APPROVE_SCHEDULE: "*/15 * * * *"
  DECLARATION_AUTOTERMINATION_SCHEDULE: "*/15 * * * *"
  MEDICATION_DISPENSE_AUTOTERMINATION_SCHEDULE: "* * * * *"
  MEDICATION_REQUEST_AUTOTERMINATION_SCHEDULE: "* * * * *"
  CLOSE_BLOCK_SCHEDULE: "0 * * * *"
  DECLARATION_REQUEST_AUTOTERMINATION_BATCH: "10"
  MEDICATION_DISPENSE_EXPIRATION: "10"
    # Database
  DB_NAME: "ops"
  DB_USER: "db"
  DB_PASSWORD: ""
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
    # Blocks database
  BLOCK_DB_NAME: "blocks"
  BLOCK_DB_USER: "db"
  BLOCK_DB_PASSWORD: ""
  BLOCK_DB_HOST: "blocks-db-svc"
  BLOCK_DB_PORT: "5432"
  BLOCK_DB_POOL_SIZE: "50"
  # EventManager Database
  EVENT_MANAGER_DB_NAME: "event_manager"
  EVENT_MANAGER_DB_USER: "db"
  EVENT_MANAGER_DB_PASSWORD: ""
  EVENT_MANAGER_DB_HOST: "db-svc.em.svc.cluster.local"
  EVENT_MANAGER_DB_PORT: "5432"
  EVENT_MANAGER_DB_POOL_SIZE: "50"
  EM_ENABLED: true
      # READ Database
  READ_DB_NAME: "ops"
  READ_DB_USER: "db"
  READ_DB_PASSWORD: ""
  READ_DB_HOST: "db-svc"
  READ_DB_PORT: "5432"
  READ_DB_POOL_SIZE: "50"
  #IL_ENDPOINT: "api-svc.il.svc.cluster.local"

resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "150Mi"
  memory_limit: "300Mi"



## DB ##
image_db:
  repository: nebo15/alpine-postgre
  tag: pglogical

env_db:
  app: "postgresql"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "ops"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"

## Blocks DB ##
resources_db:
  cpu: "50m"
  memory: "112Mi"
  limits_memory: "1Gi"
  storage: "2Gi"
  storage_ops: "2Gi"

log_backups:
  enabled: false
  period_in_seconds: "30"
  image: google/cloud-sdk:198.0.0-alpine
  log_folder: /var/lib/postgresql/data/pg_log
  account:
  key_file_path:
  bucket:

env_blocks_db:
  app: "psql-blocks"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "blocks"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"
  port_name: psql-blocks

# resources_db:
#   cpu: "50m"
#   memory: "128Mi"
#   limits_memory: "1Gi"
#   storage: "50Gi"

resources_ops_scheduler:
  cpu:
  memory:
  cpu_limit:
  memory_limit: 

resources_deactivate_declaration_consumer:
  cpu:
  memory:
  cpu_limit:
  memory_limit: 

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

env: demo
storageClass: demo

deployNotification:
  enabled: false
  slackEndpoint:
  slackChannel:
  slackUsername:
  slackEmoji:
