
## FE ##
image_fe:
   image: edenlabllc/uaddresses.web
   tag: "0.1.21"
env_fe:
  containerPort: 8080
  API_ENDPOINT: "http://api.<example.com>/api/uaddresses"
  AUTH_ENDPOINT: "http://api.<example.com>"
  CLIENT_ID:  ""
  CLIENT_SECRET: ""
  OAUTH_REDIRECT_URL: "http://uaddresses.<example.com>/auth/redirect"
  OAUTH_URL: "http://auth.<example.com>/sign-in"
  cpu: 50m
  memory: 50Mi
  replicas: 1
  revisionHistoryLimit: 3
  app: fe

ingress:
  host: uaddresses.<example.com>

## API ##
#Docker image and tag for api
image_api:
  repository: edenlabllc/uaddresses_api
  tag: "3.1.1"

env_api:
##RPC
  NAMESPACE: "uaddresses"
   # --- Phoenix---#
   #APP_PORT
  port: "4000"
  #APP_HOST
  host: ""
  #APP_SECRET_KEY
  secret: ""
  ERLANG_COOKIE: ""
    # Database
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
    # App migrations
  DB_MIGRATE: "true"
resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "128Mi"
  memory_limit: "300Mi"



## DB ##
image_db:
  repository: nebo15/alpine-postgre
  tag: pglogical

env_db:
  app: "postgresql"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "uaddresses"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"

resources_db:
  cpu: "50m"
  memory: "112Mi"
  limits_memory: "1Gi"
  storage: "2Gi"

log_backups:
  enabled: false
  period_in_seconds: "30"
  image: google/cloud-sdk:198.0.0-alpine
  log_folder: /var/lib/postgresql/data/pg_log
  account: 
  key_file_path:
  bucket:

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

env: demo
storageClass: demo

deployNotification:
  enabled: false
  slackEndpoint:
  slackChannel:
  slackUsername:
  slackEmoji:
