image_fe:
  image: edenlabllc/mithril.web
  tag: "1.0.56"
env_fe:
  containerPort: 8080
  CLIENT_ID:  ""
  CLIENT_SECRET: ""
  OAUTH_REDIRECT_URL: "http://mithril.<example.com>/auth/redirect"
  API_ENDPOINT: "http://api.<example.com>"
  OAUTH_URL: "http://auth.<example.com>/sign-in"
  cpu: 50m
  memory: 50Mi
  replicas: 1
  revisionHistoryLimit: 3
  app: fe
loadBalancerIP:

ingress:
  active: true
  host: mithril.<example.com>

## API ##
#Docker image and tag for api
image_api:
  repository: edenlabllc/mithril_api
  tag: "4.1.2"

image_mithril_scheduler:
  repository: edenlabllc/mithril_scheduler
  tag: "0.1.1"
  name: "mithril-scheduler"

env_api:
  #RPC
  NAMESPACE: mithril
   # --- Phoenix---#
   #APP_PORT
  LOG_LEVEL: "info"
  port: "4000"
  #APP_HOST
  host: ""
  #APP_SECRET_KEY
  secret: ""
  ERLANG_COOKIE: ""
    # Database
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
  # App migrations and seeds
  DB_MIGRATE: "true"
  LOAD_FIXTURES: "true"
  # OTP
  OTP_ENDPOINT: "http://api-svc.verification"
  OTP_REQUEST_TIMEOUT: "30000"
  # MPI
  MPI_ENDPOINT: "http://api-svc.mpi"
  MPI_REQUEST_TIMEOUT: "30000"
  # Digital signature
  DIGITAL_SIGNATURE_ENDPOINT: "http://api-svc.digital-signature"
  DIGITAL_SIGNATURE_REQUEST_TIMEOUT: "30000"
  DIGITAL_SIGNATURE_ENABLED: "false"
  # two-factor authentication
  USER_2FA_ENABLED: "false"
  SMS_ENABLED: "false"
  OTP_SMS_TEMPLATE: "Код підтвердження: <otp.code>"
  USER_LOGIN_ERROR_MAX: "3"
  USER_OTP_ERROR_MAX: "3"
  OTP_LIFETIME: "300" # seconds
  OTP_LENGTH: "4"
  OTP_MAX_ATTEMPTS: "3"
  OTP_SEND_TIMEOUT: "1" # minutes
  MAX_FAILED_LOGINS_PERIOD: "5" # minutes
  OTP_EXPIRATION_SCHEDULE: "*/5 * * * *"
  TOKEN_DELETING_SCHEDULE: "0,30 1-4 * * *"    
  TOKEN_EXPIRATION_SCHEDULE: "* * * * *"
  JWT_SECRET: ""
    # ReCAPTCHA
  RECAPTCHA_ENABLED: "false"  
  RECAPTCHA_VERIFY_URL: "https://www.google.com/recaptcha/api/siteverify"
  RECAPTCHA_SECRET: ""  
  # tokens
  AUTH_ACCESS_TOKEN_LIFETIME: "3600"
  AUTH_REFRESH_TOKEN_LIFETIME: "1209600"
  # minutes
  PASSWORD_EXPIRATION_DAYS: "900"
  TOKEN_TTL_AFTER_EXPIRATION_DAYS: "30"
  JWT_LOGIN_TTL: "15"
  SENSITIVE_DATA_IN_RESPONSE_ENABLED: "true"
  TRUSTED_CLIENT_IDS: ""

env_mithril_scheduler:
  #RPC
  NAMESPACE: mithril
  TOKEN_EXPIRATION_SCHEDULE: "* 0-4 * * *"
  TOKEN_DELETING_SCHEDULE: "* 1-4 * * *"
  OTP_EXPIRATION_SCHEDULE: "*/5 * * * *"
  TOKEN_TTL_AFTER_EXPIRATION_DAYS: "30"
  #APP_SECRET_KEY
  ERLANG_COOKIE: "admin"
    # Database
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_POOL_SIZE: "50"
  DB_USER: "db"
  DB_NAME: "mithril"
  PASSWORD_EXPIRATION_DAYS: "900"
  OTP_ENDPOINT: "http://api-svc.verification"
  OTP_REQUEST_TIMEOUT: "30000"
  # MPI
  MPI_ENDPOINT: "http://api-svc.mpi"
  MPI_REQUEST_TIMEOUT: "30000"
  # Digital signature
  DIGITAL_SIGNATURE_ENDPOINT: "http://api-svc.digital-signature"
  DIGITAL_SIGNATURE_REQUEST_TIMEOUT: "30000"
  DIGITAL_SIGNATURE_ENABLED: "true"
  # two-factor authentication
  USER_2FA_ENABLED: "false"
  SMS_ENABLED: "true"
  OTP_SMS_TEMPLATE: "Код підтвердження: <otp.code>"
  USER_LOGIN_ERROR_MAX: "3"
  USER_OTP_ERROR_MAX: "3"
  OTP_LIFETIME: "300" # seconds
  OTP_LENGTH: "4"
  OTP_MAX_ATTEMPTS: "3"
  OTP_SEND_TIMEOUT: "1" # minutes
  MAX_FAILED_LOGINS_PERIOD: "1" # minutes
  OTP_EXPIRATION_SCHEDULE: "*/5 * * * *"
  TOKEN_DELETING_SCHEDULE: "* 1-4 * * *"
  TOKEN_EXPIRATION_SCHEDULE: "* * * * *"
  JWT_SECRET: ""
  # ReCAPTCHA
  RECAPTCHA_ENABLED: "false"
  RECAPTCHA_VERIFY_URL: "https://www.google.com/recaptcha/api/siteverify"
  RECAPTCHA_SECRET: ""
  # tokens
  AUTH_ACCESS_TOKEN_LIFETIME: "2592000"
  AUTH_REFRESH_TOKEN_LIFETIME: "1209600"
  # minutes
  TOKEN_TTL_AFTER_EXPIRATION_DAYS: "30"
  JWT_LOGIN_TTL: "15"
  SENSITIVE_DATA_IN_RESPONSE_ENABLED: "true"
  TRUSTED_CLIENT_IDS: ""  


storageClass: "dev"  

resources_api:
  cpu: "10m"
  cpu_limit: "1"
  memory: "112Mi"
  memory_limit: "400Mi"

## DB ##
image_db:
  repository: nebo15/alpine-postgre
  tag: pglogical

env_db:
  app: "postgresql"
  version: "9.6"
  #DB_USER: API - POSTGRES_DB: DB
  POSTGRES_USER: "db"
  #DB_PASSWORD: API and DB
  POSTGRES_PASSWORD: ""
  PGDATA: "/var/lib/postgresql/data"
  #DB_NAME: API
  POSTGRES_DB: "mithril"
  REPLICATOR_USER: "pghoard"
  REPLICATOR_PASSWORD: ""
  db_port: "5432"

resources_db:
  cpu: "50m"
  memory: "112Mi"
  limits_memory: "1Gi"
  storage: "10Gi"

log_backups:
  enabled: false
  period_in_seconds: "30"
  image: google/cloud-sdk:198.0.0-alpine
  log_folder: /var/lib/postgresql/data/pg_log
  account:
  key_file_path:
  bucket:

rollingUpdate:
  maxSurge: "1"
  maxUnavailable: "1"

storageClass: demo
env: demo

deployNotification:
  enabled: false
  slackEndpoint:
  slackChannel:
  slackUsername:
  slackEmoji:
